#!/bin/bash
file=$1
speedtotal=0; avg_rate=0;n=1
for i in $(awk '{print $7}' $file); do
speedtotal=`awk -v speed=$i -v speedtotal=$speedtotal 'BEGIN{speedtotal=(speedtotal+speed); print speedtotal}'`
avg_rate=`awk -v speedtotal=$speedtotal -v n=$n 'BEGIN{print speedtotal/n}'`
echo $avg_rate
let n=n+1
done
